CREATE OR REPLACE PACKAGE MDL.GererVacation as
	PROCEDURE InsertVacation(p_IDATELIER VACATION.IDATELIER%type,p_HEUREDEBUT VACATION.HEUREDEBUT%type,p_HEUREFIN VACATION.HEUREFIN%type);
	PROCEDURE UpdateVacation(p_NUMERO VACATION.NUMERO%type,p_HEUREDEBUT VACATION.HEUREDEBUT%type,p_HEUREFIN VACATION.HEUREFIN%type);
END GererVacation;

CREATE OR REPLACE PACKAGE BODY GererVacation AS 
  PROCEDURE InsertVacation(p_IDATELIER VACATION.IDATELIER%typep_HEUREDEBUT VACATION.HEUREDEBUT%type,p_HEUREFIN VACATION.HEUREFIN%type) 
    IS 
    BEGIN 
    INSERT INTO Vacation(IDATELIER,NUMERO,HEUREDEBUT,HEUREFIN) VALUES (p_IDATELIER,SEQVACATION.nextval,p_HEUREDEBUT,p_HEUREFIN ); 
  END InsertVacation; 
 
  PROCEDURE UpdateVacation(p_NUMERO VACATION.NUMERO%type,p_HEUREDEBUT VACATION.HEUREDEBUT%type,p_HEUREFIN VACATION.HEUREFIN%type) 
    IS 
    BEGIN 
    Update Vacation SET (HEUREDEBUT=p_HEUREDEBUT,HEUREFIN=p_HEUREFIN WHERE NUMERO = p_NUMERO) 
  END UpdateVacation; 
END GererVacation;  

