CREATE or REPLACE PACKAGE BODY GererTheme as

CREATE OR REPLACE PROCEDURE InsertTheme(
    p_IDATELIER Theme.IDATELIER%type,
    p_NUMERO Theme.NUMERO%type,
    p_LIBELLETHEME Theme.HEUREDEBUT%type
)
IS
BEGIN
	INSERT INTO Theme VALUES (
		p_IDATELIER,
		p_NUMERO,
		p_LIBELLETHEME
END;


