create or replace PACKAGE GERERPARTICIPANT AS 

 PROCEDURE InsertParticipant(
 p_ID PARTICIPANT.ID%type ,
 p_DATEENREGISTREMENTARRIVEE VARCHAR2, 
 p_CLEWIFI PARTICIPANT.CLEWIFI%type
 );

END GERERPARTICIPANT;
END GERERPARTICIPANT;

create or replace PACKAGE BODY GERERPARTICIPANT AS
 PROCEDURE InsertParticipant(
 p_ID PARTICIPANT.ID%type,
 p_DATEENREGISTREMENTARRIVEE VARCHAR2, 
 p_CLEWIFI PARTICIPANT.CLEWIFI%type
 )
IS
BEGIN
    UPDATE PARTICIPANT
    SET DATEENREGISTREMENTARRIVEE = TO_DATE(p_DATEENREGISTREMENTARRIVEE,'DD/MM/YYYY HH24:MI:SS'),CLEWIFI = p_CLEWIFI
    WHERE ID= p_ID;
END InsertParticipant;
END GERERPARTICIPANT;