CREATE or REPLACE PACKAGE BODY GererAtelier as


CREATE OR REPLACE PROCEDURE InsertAtelier(
    p_ID Atelier.ID%type,
    p_LIBELLEATELIER Atelier.LIBELLEATELIER%type,
    p_NBPLACESMAXI Atelier.NBPLACESMAXI%type
)
IS
BEGIN
	INSERT INTO Atelier VALUES (
		p_ID Atelier,
		p_LIBELLEATELIER,
		p_NBPLACESMAXI
END;


