CREATE OR REPLACE PACKAGE GERERPARTICIPANT AS 

 PROCEDURE InsertParticipant(
 p_NOMPARTICIPANT PARTICIPANT.NOMPARTICIPANT%type , 
 p_PRENOMPARTICIPANT PARTICIPANT.PRENOMPARTICIPANT%type, 
 p_ADRESSEPARTICIPANT1 PARTICIPANT.ADRESSEPARTICIPANT1%type, 
 p_ADRESSEPARTICIPANT2 PARTICIPANT.ADRESSEPARTICIPANT2%type, 
 p_CPPARTICIPANT PARTICIPANT.CPPARTICIPANT%type, 
 p_VILLEPARTICIPANT PARTICIPANT.VILLEPARTICIPANT%type, 
 p_TELPARTICIPANT PARTICIPANT.TELPARTICIPANT%type, 
 p_MAILPARTICIPANT PARTICIPANT.MAILPARTICIPANT%type, 
 p_DATEINSCRIPTION PARTICIPANT.DATEINSCRIPTION%type, 
 p_DATEENREGISTREMENTARRIVEE PARTICIPANT.DATEENREGISTREMENTARRIVEE%type, 
 p_CLEWIFI PARTICIPANT.CLEWIFI%type
 );

END GERERPARTICIPANT;

CREATE OR REPLACE PACKAGE BODY GERERPARTICIPANT AS
 PROCEDURE InsertParticipant(
 p_NOMPARTICIPANT PARTICIPANT.NOMPARTICIPANT%type , 
 p_PRENOMPARTICIPANT PARTICIPANT.PRENOMPARTICIPANT%type, 
 p_ADRESSEPARTICIPANT1 PARTICIPANT.ADRESSEPARTICIPANT1%type, 
 p_ADRESSEPARTICIPANT2 PARTICIPANT.ADRESSEPARTICIPANT2%type, 
 p_CPPARTICIPANT PARTICIPANT.CPPARTICIPANT%type, 
 p_VILLEPARTICIPANT PARTICIPANT.VILLEPARTICIPANT%type, 
 p_TELPARTICIPANT PARTICIPANT.TELPARTICIPANT%type, 
 p_MAILPARTICIPANT PARTICIPANT.MAILPARTICIPANT%type, 
 p_DATEINSCRIPTION PARTICIPANT.DATEINSCRIPTION%type, 
 p_DATEENREGISTREMENTARRIVEE PARTICIPANT.DATEENREGISTREMENTARRIVEE%type, 
 p_CLEWIFI PARTICIPANT.CLEWIFI%type
 )
IS
BEGIN
    INSERT INTO PARTICIPANT(ID,NOMPARTICIPANT,PRENOMPARTICIPANT,ADRESSEPARTICIPANT1,ADRESSEPARTICIPANT2,CPPARTICIPANT,VILLEPARTICIPANT,TELPARTICIPANT,MAILPARTICIPANT,DATEINSCRIPTION,DATEENREGISTREMENTARRIVEE,CLEWIFI)
    VALUES(SEQPARTICIPANT.nextval,p_NOMPARTICIPANT,p_PRENOMPARTICIPANT,p_ADRESSEPARTICIPANT1,p_ADRESSEPARTICIPANT2,p_CPPARTICIPANT,p_VILLEPARTICIPANT,p_TELPARTICIPANT,p_MAILPARTICIPANT,p_DATEINSCRIPTION,p_DATEENREGISTREMENTARRIVEE,p_CLEWIFI);
END InsertParticipant;
END GERERPARTICIPANT;